# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f961952b6e1df7662ba1c694ec339c7b121b5ef632d0ffc1d4ecb656aed1c17e4a5e3e8e742f1d51367d358ec94b74d88a3c8499e83b2b33fa42be792eba575a

test:
  secret_key_base: 5277780e423bd1a31aec0e6aaf2fe255473f4aec92f8466306a0ac91a8b12e9364b93fb4b55accfa18adcfff934f8ff3b83f1cdab46f263395bcfe99ff26a3af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
